### PR TITLE
Instrumentation for metrics collection

### PR DESCRIPTION
**Pull request by moritzraho**
## Description
copy of #52 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by moritzraho** [comment]
Ready for another round of code review, but note that it still requires:
[ ] E2E testing
[ ] `@adobe/aio-lib-metrics` release

cc @purplecabbage @sandeep-paliwal

**Comment by purplecabbage** [comment]
I did the same thing, this needs to be changed to be consistent with the rest.
I am doing my-apps, action-validators, tvm, login-function and their deployment scripts.

**Comment by purplecabbage** [comment]
Please see #57

**Comment by moritzraho** [comment]
Can we discuss the changes ?
I am seeing two differences: 
- using `metrics-url` vs `metricsUrl`, problem is all other parameters in TVM use camel case so it wouldn't be very consistent..
- sending an `error_count` for both 4xx and 5xx errors, but I think we should differentiate as 5xxs are actual errors on our side and 4xxs just user failures. Maybe you already discussed this, please let me know.

Any other difference I should consider?

**Comment by moritzraho** [comment]
added some changes to clean it a bit up, feel free to add new comments

**Comment by purplecabbage** [comment]
Yes consistency is an issue, unfortunately I am trying to tackle the same change across 5 repos, and we essentially have 4 standards ...
Login action manifest uses
  inputs:
    `LOG_LEVEL: $LOG_LEVEL`
Validators uses
  ` __VALIDATOR_LOG_LEVEL: info`
Tvm uses
  `s3Bucket: $S3_BUCKET`
 MyApps uses
   `cli-env: $AIO_CLI_ENV`
Also note that
`params['metrics-url']` IS consistent with `params.__ow_headers['x-request-id']`

Regardless, we can seek a single standard and consensus when there is room in our backlog.
I'll make changes for 4xx / 5xx

**Comment by moritzraho** [comment]
ok agreed thank you @purplecabbage

**Pull request merged**
